<?php
/*=======================================================\
|                        FrontHrm                        |
|--------------------------------------------------------|
|   Creator: Phương <trananhphuong83@gmail.com>          |
|   Date :   09-Jul-2017                                 |
|   Description: Frontaccounting Payroll & Hrm Module    |
|   Free software under GNU GPL                          |
|                                                        |
\=======================================================*/

include_once($path_to_root.'/modules/FrontHrm/includes/db/employee_db.inc');
include_once($path_to_root.'/modules/FrontHrm/includes/db/department_db.inc');
include_once($path_to_root.'/modules/FrontHrm/includes/db/job_position_db.inc');
include_once($path_to_root.'/modules/FrontHrm/includes/db/overtime_db.inc');
include_once($path_to_root.'/modules/FrontHrm/includes/db/attendance_db.inc');
include_once($path_to_root.'/modules/FrontHrm/includes/db/account_db.inc');
include_once($path_to_root.'/modules/FrontHrm/includes/db/salary_structure_db.inc');
include_once($path_to_root.'/modules/FrontHrm/includes/db/payslip_db.inc');
include_once($path_to_root.'/modules/FrontHrm/includes/db/employee_db_banking.inc');
include_once($path_to_root.'/modules/FrontHrm/includes/db/doc_db.inc');
include_once($path_to_root.'/modules/FrontHrm/includes/db/grade_db.inc');
include_once($path_to_root.'/modules/FrontHrm/includes/db/leave_db.inc');