DROP TABLE IF EXISTS `0_employee`;
DROP TABLE IF EXISTS `0_department`;
DROP TABLE IF EXISTS `0_salaryscale`;
DROP TABLE IF EXISTS `0_overtime`;
DROP TABLE IF EXISTS `0_attendance`;
DROP TABLE IF EXISTS `0_payroll_account`;
DROP TABLE IF EXISTS `0_payroll_structure`;
DROP TABLE IF EXISTS `0_salary_structure`;
DROP TABLE IF EXISTS `0_payslip`;
DROP TABLE IF EXISTS `0_payslip_details`;
DROP TABLE IF EXISTS `0_employee_trans`;
DELETE FROM `0_sys_prefs` WHERE `0_sys_prefs`.`name` = 'payroll_deductleave_act';
DELETE FROM `0_sys_prefs` WHERE `0_sys_prefs`.`name` = 'payroll_month_work_days';
DELETE FROM `0_sys_prefs` WHERE `0_sys_prefs`.`name` = 'payroll_overtime_act';
DELETE FROM `0_sys_prefs` WHERE `0_sys_prefs`.`name` = 'payroll_payable_act';
DELETE FROM `0_sys_prefs` WHERE `0_sys_prefs`.`name` = 'payroll_work_hours';
