DROP TABLE IF EXISTS `0_employee`;
DROP TABLE IF EXISTS `0_department`;
DROP TABLE IF EXISTS `0_salaryscale`;
DROP TABLE IF EXISTS `0_overtime`;
DROP TABLE IF EXISTS `0_attendance`;
DROP TABLE IF EXISTS `0_payroll_account`;
DROP TABLE IF EXISTS `0_payroll_structure`;
DROP TABLE IF EXISTS `0_salary_structure`;
DROP TABLE IF EXISTS `0_payslip_detail`;
